name: CI

on: [push]

jobs:
    build:
        runs-on: macOS-latest
        steps:
          - name: Checkout 
            uses: actions/checkout@v1
          - name: Install Tools
            run: |
                gem install xcpretty
          - name: Build and Test
            run: |
                cd "Framework"
                echo $(pwd)
                xcodebuild test -scheme MIKMIDI | xcpretty
